### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by DailyTinker91** [gentoomaniac/VaultMinimapButton#1]
I had been using the addon for the better part of the without noticing an issue. I enabled Gatherer and Farmhud addons and the game started to freeze. Shortly after, everytime I hovered over the minimap, other buttons, or tried to use farmhud the game would freeze for a moment, stop responding, then sometimes picking back up or occasionally crashed. I disable Vaultmini and haven't had any of those issues. 

I also run
-Elvui
-Bigwigs
-Fishing Buddy
-!Details
-Weakauras
-Auctionator

**Comment by gentoomaniac** [comment]
Hmmm... I can't really see a connection there besides the shipped dependencies.
I can try an build a version that doesn't include dependency libs, maybe that solves your issue.

**Comment by gentoomaniac** [comment]
i pushed an update not sure though how one can download the package
https://www.curseforge.com/wow/addons/vaultminimapbutton/files/3192291

if you want to manually try:
try removing the libs folder and potentially the embeds.xml (and the reference to it int the .toc file)

As long as your other addons load those dependencies all should be fine and load. I'd be interested to hear if that makes any difference.

**Comment by DailyTinker91** [comment]
I appreciate the reply, but it was like I was trying to read a second
language. I wish I knew more about coding to help. I just appreciate what
you've done and wanted to let you know of my problem, and that maybe others
might also encounter it. Thanks

**Comment by gentoomaniac** [comment]
Let me see if i can somehow reproduce it. As you said it worked before i'm pretty sure i know roughly what the problem is, but not sure why and how to fix it.

**Comment by gentoomaniac** [comment]
Whoop, one thing that caught my attention just now: Gatherer is not maintained any more and received it's last update in legion.
So it might very well be broken as xpac per xpac there is lot's of changes in the game affecting/breaking addons.

I switched to https://www.curseforge.com/wow/addons/gathermate2 a while back.

**Comment by DailyTinker91** [comment]
Thanks ill have to take a look at that.

**Comment by gentoomaniac** [comment]
Hope that solves it. In any way: your feedback is much appreciated :) Thank you.
